openapi: 3.0.1
info:
  title: LDC Hackathon | UBS api
  description: This is the UBS api to facilitate the data access in all care units in Brazil.
  version: '1.2'
servers:
  - url: 'https://api-ldc-hackathon.herokuapp.com'
paths:
  /api/ubs/{page}:
    get:
      description: Get UBS list using pagination
      parameters:
      - name: page
        in: path
        description: Pagination parameter. eg. 1 of x
        required: true
        schema:
          type: integer
          example: 1, Page   # <----
        example: 1 # Overrides schema-level example
      responses:
        '200':
          description: 'JSON list of UBS with the pagination information itself'
      servers:
        - url: 'https://api-ldc-hackathon.herokuapp.com'
  /api/ubs/city:
    post:
      description: Get UBS list by city
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                page:
                  type: integer
            examples:
              '0':
                value: "{\"city\": \"Jacareí\", \"page\": 1\"}"
      responses:
        '200':
          description: 'JSON list of UBS with the pagination information itself'
      servers:
        - url: 'https://api-ldc-hackathon.herokuapp.com'
    servers:
      - url: 'https://api-ldc-hackathon.herokuapp.com'