openapi: 3.0.1
info:
  title: LDC Hackathon | UBS api
  description: This is the UBS api to facilitate the data access in all care units in Brazil.
  version: '1.0'
servers:
  - url: 'https://api-ldc-hackathon.herokuapp.com'
paths:
  /api/ubs/{page}:
    get:
      description: Get UBS list using pagination
      parameters:
      - name: page
        in: path
        description: Pagination parameter. eg. 1 of x
        required: true
        schema:
          type: integer
          example: 1, Page   # <----
        example: 1 # Overrides schema-level example
      responses:
        '200':
          description: 'JSON list of UBS with the pagination information itself'
      servers:
        - url: 'https://api-ldc-hackathon.herokuapp.com'
    servers:
      - url: 'https://api-ldc-hackathon.herokuapp.com'